/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import javax.swing.ButtonGroup;

/**
 *
 * @author asus
 */
public class CelciusToFahreinheitGUI extends javax.swing.JFrame {

    private ButtonGroup buttonGroup1;

    /**
     * Creates new form CelciusToFahreinheitGUI
     */
    public CelciusToFahreinheitGUI() {
        initComponents();
        
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        input = new javax.swing.JTextField();
        sbSuhu = new javax.swing.JComboBox<>();
        rbCelcius = new javax.swing.JRadioButton();
        rbKelvin = new javax.swing.JRadioButton();
        rbFahrenheit = new javax.swing.JRadioButton();
        rbReamur = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        hasilLabel = new javax.swing.JLabel();
        convertButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        input.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputActionPerformed(evt);
            }
        });
        jPanel1.add(input, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 30, 230, -1));

        sbSuhu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Celcius", "Fahrenheit", "Kelvin", "Reamur" }));
        sbSuhu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sbSuhuActionPerformed(evt);
            }
        });
        jPanel1.add(sbSuhu, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, 230, -1));
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup1.add(rbCelcius);
        buttonGroup1.add(rbKelvin);
        buttonGroup1.add(rbFahrenheit);
        buttonGroup1.add(rbReamur);

        rbCelcius.setText("Celcius");
        rbCelcius.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbCelciusActionPerformed(evt);
            }
        });
        jPanel1.add(rbCelcius, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 110, -1, -1));

        rbKelvin.setText("Kelvin");
        rbKelvin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbKelvinActionPerformed(evt);
            }
        });
        jPanel1.add(rbKelvin, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 140, -1, -1));

        rbFahrenheit.setText("Fahrenheit");
        jPanel1.add(rbFahrenheit, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 110, -1, -1));

        rbReamur.setText("Reamur");
        jPanel1.add(rbReamur, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 140, -1, -1));

        jLabel1.setText("Nilai");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        jLabel2.setText("Suhu");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));

        jLabel3.setText("Convert Suhu");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, -1));

        jLabel4.setText("Hasil");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 40, 20));

        hasilLabel.setText("=");
        jPanel1.add(hasilLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 220, -1, -1));

        convertButton.setText("Convert");
        convertButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                convertButtonActionPerformed(evt);
            }
        });
        jPanel1.add(convertButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 170, 230, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 480, 310));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputActionPerformed

    private void sbSuhuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sbSuhuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sbSuhuActionPerformed

    private void rbKelvinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbKelvinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbKelvinActionPerformed

    private void rbCelciusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbCelciusActionPerformed
             // TODO add your handling code here:
    }//GEN-LAST:event_rbCelciusActionPerformed

    private void convertButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_convertButtonActionPerformed
        convertButton.addActionListener(new java.awt.event.ActionListener() {
    public void actionPerformed(java.awt.event.ActionEvent evt) {
        try {
            double inputValue = Double.parseDouble(input.getText());
            String result = "";
            
            if (rbCelcius.isSelected()) {
                result = convertFromCelsius(inputValue, sbSuhu.getSelectedItem().toString());
            } else if (rbKelvin.isSelected()) {
                result = convertFromKelvin(inputValue, sbSuhu.getSelectedItem().toString());
            } else if (rbFahrenheit.isSelected()) {
                result = convertFromFahrenheit(inputValue, sbSuhu.getSelectedItem().toString());
            } else if (rbReamur.isSelected()) {
                result = convertFromReamur(inputValue, sbSuhu.getSelectedItem().toString());
            }

            hasilLabel.setText("= " + result);
        } catch (NumberFormatException e) {
            hasilLabel.setText("Input tidak valid");
        }
    }

   private String convertFromCelsius(double value, String targetUnit) {
    double result = 0;
    switch (targetUnit) {
        case "Fahrenheit":
            result = (value * 9/5) + 32;
            break;
        case "Kelvin":
            result = value + 273.15;
            break;
        case "Reamur":
            result = value * 4/5;
            break;
        default:
            result = value;
            break;
    }
    return String.format("%.2f", result);
}

private String convertFromKelvin(double value, String targetUnit) {
    double celsius = value - 273.15;
    return convertFromCelsius(celsius, targetUnit);
}

private String convertFromFahrenheit(double value, String targetUnit) {
    double celsius = (value - 32) * 5/9;
    return convertFromCelsius(celsius, targetUnit);
}

private String convertFromReamur(double value, String targetUnit) {
    double celsius = value * 5/4;
    return convertFromCelsius(celsius, targetUnit);
}

        });
    // TODO add your handling code here:
    }//GEN-LAST:event_convertButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CelciusToFahreinheitGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CelciusToFahreinheitGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CelciusToFahreinheitGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CelciusToFahreinheitGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CelciusToFahreinheitGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton convertButton;
    private javax.swing.JLabel hasilLabel;
    private javax.swing.JTextField input;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton rbCelcius;
    private javax.swing.JRadioButton rbFahrenheit;
    private javax.swing.JRadioButton rbKelvin;
    private javax.swing.JRadioButton rbReamur;
    private javax.swing.JComboBox<String> sbSuhu;
    // End of variables declaration//GEN-END:variables
}
